### ISSUE TITLE
能不能更新一下这个例子

### ISSUE THREAD

**Issue by anchengjian** [hilongjw/vue-vueRouter-webpack-example#1]
能不能更新一下这个例子。
比如最新出来的热切等等，我想直接用这个例子来开始我的blog。谢谢

**Comment by hilongjw** [comment]
建议使用 vue-cli https://github.com/vuejs/vue-cli

**Comment by anchengjian** [comment]
妈蛋，你根本没更新

**Comment by hilongjw** [comment]
2333，弃坑了，有了vue-cli 这个example存在意义不大啊
